### ISSUE TITLE
Sending POST requests without submitting a form

### ISSUE THREAD

**Issue by 5j9** [jmcarp/robobrowser#27]
If possible please provide a more convenient way for direct sending of POST requests so that it will automatically _update_state.

https://stackoverflow.com/questions/23737719/how-to-make-post-request-in-robobrowser-python

**Comment by jmcarp** [comment]
I modified `Browser#open` to take an optional `method` argument. For the behavior you're looking for, you can now use `browser.open(url, method='post')`.
