### ISSUE TITLE
forms and javascript / ajax does not work?

### ISSUE THREAD

**Issue by YAmikep** [jmcarp/robobrowser#36]
Hi,

Nice work.
However, I am having some issues with some forms and ajax requests.
Do you confirm that it does not work if a form is sent via javascript and the results are displayed on the same page via ajax?

Thanks
Michael

**Comment by pohmelie** [comment]
Of course it doesn't work. robobrowser = requests + beautifulsoup4. There is no js engine, and no (AFAIK), ajax emulation. Cause definetly you can do ajax via requests (I have some experience), but it's common situation when ajax is not just "send form values", but "send some calculated values" instead. So, you should analyse your target site and get proper request, then just send it through browser.session. Which is just requests.session object. Sorry for my english :)

**Comment by YAmikep** [comment]
Ok thanks, maybe it would be a good idea to add this limitation in the documentatio because the library says that it is used to browse the web so someone could expect it to work to browse any website.

Thanks
