### ISSUE TITLE
Installing via pip fails

### ISSUE THREAD

**Issue by Dashius** [jmcarp/robobrowser#39]
Installing via pip produces an error. I'm using python 3.4.

    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/.../.../robobrowser/setup.py", line 38, in <module>
    
        for requirement in parse_requirements('requirements.txt')
    
      File "/.../.../robobrowser/setup.py", line 37, in <listcomp>
    
        str(requirement.req)
    
      File "/.../.../python3.4/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    
        "parse_requirements() missing 1 required keyword argument: "
    
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /.../.../robobrowser

**Comment by asmaier** [comment]
I have the same issue. I'm using python 2.7.9.

**Comment by asmaier** [comment]
See also here: http://stackoverflow.com/questions/27869152/heroku-typeerror-parse-requirements-missing-1-required-keyword-argument-ses
