### ISSUE TITLE
Disabled <input> elements should not be submitted.

### ISSUE THREAD

**Issue by 5j9** [jmcarp/robobrowser#42]
According to [1] and [2], the disabled attribute prevents value from being submitted.

It seems that robobrowser does not check if elements are disabled or not. In my case there was a disabled checkbox in a form that was submitted unexpectedly.

[1]: http://www.w3.org/TR/html401/interact/forms.html#h-17.12
[2]: http://www.w3.org/TR/html5/forms.html

**Comment by jmcarp** [comment]
Good catch! This is fixed in https://github.com/jmcarp/robobrowser/commit/c249037e2f3b9eaea84b2ef7c40f6d3c898ae031 and will be released soon.
