### ISSUE TITLE
browser.get_form - forms with a text area returns a prefixed \r when empty and \r\rn when filled

### ISSUE THREAD

**Issue by tanner-pm** [jmcarp/robobrowser#63]
I am running into an issue with forms that have text areas. When grabbing the form using browser.get_form all blank text areas return a \r and when submitted now have a new line.

Also, all non-blank text areas are prefixed with a \r\n to the front of it when pulling the form.

**Comment by 0xLuz** [comment]
Have you tried to use [.strip()](https://docs.python.org/2/library/string.html#string.strip) over the field return?
I normally use it to clean the `string` return from tables or inputs while scrapping.

```py
>>> string = "\n\rHello World"
>>> string
'\n\rHello World'
>>> string.strip()
'Hello World'
>>> 
```

**Comment by tanner-pm** [comment]
Yep. That's what I ended up doing. Thanks for the reply!
